version: "3.9"

services: 
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 3060:3000
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 8080:80
    restart: always